script for public gpg key upload
blinkhealth/eng-onboarding pull request #27
Opened 2023-09-13 06:22 UTC by vishnureddy-blink

https://blinkhealth.atlassian.net/browse/INFRAENG-3504

2023-09-13 09:49 UTC, sachinchemmala requested changes

2023-09-13 09:49 UTC, sachinchemmala commented on provisioning/onboard/public_key_upload.sh
> +git clone git@github.com:blinkhealth/eng-onboarding.git
It's better to clone the repo to a temp directory

2023-09-13 09:49 UTC, sachinchemmala commented on provisioning/onboard/public_key_upload.sh
> +cd "$REPO_NAME"
Instead of `cd` we should use explicit path. Otherwise debugging will be little tough

2023-09-13 09:49 UTC, sachinchemmala commented on provisioning/onboard/public_key_upload.sh
> +if [ -f "provisioning/keys/$MACHINE_USERNAME.asc" ]; then
use explicit path

2023-09-13 09:49 UTC, sachinchemmala commented on provisioning/onboard/public_key_upload.sh
> +    mkdir -p provisioning/keys
same as above

2023-09-13 09:49 UTC, sachinchemmala commented on provisioning/onboard/public_key_upload.sh
> +    REPO_NAME="eng-onboarding"
duplicate var

2023-09-13 09:49 UTC, sachinchemmala commented on provisioning/onboard/public_key_upload.sh
> +    BASE_BRANCH="main"
keep all variables in the beginning of the script

2023-09-13 09:49 UTC, sachinchemmala commented on provisioning/onboard/public_key_upload.sh
> +cd ..
us explicit paths instead of `cd`

2023-09-13 09:49 UTC, sachinchemmala commented on provisioning/onboard/public_key_upload.sh
> +        echo "Failed to create a pull request."
If it's failed, how do we know the actual reason for failure ? This message is not very helpful

2023-09-13 09:49 UTC, sachinchemmala commented on provisioning/onboard/public_key_upload.sh
> +rm -rf "$REPO_NAME"
We should print some message for cleaning up things too. What's is cleaning up, if it's failure or success or not.

2023-09-13 09:49 UTC, sachinchemmala commented
I just tried the script again as shown below, it's throwing different errors.

```
╰─$ bash ~/test/pr.sh
/Users/sachin.chemmala/test/pr.sh: line 7: read: `Enter your GitHub personal access token: ': not a valid identifier
Cloning into 'eng-onboarding'...
remote: Enumerating objects: 121, done.
remote: Counting objects: 100% (51/51), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 121 (delta 36), reused 22 (delta 20), pack-reused 70
Receiving objects: 100% (121/121), 36.38 KiB | 163.00 KiB/s, done.
Resolving deltas: 100% (55/55), done.
Switched to a new branch 'sachin.chemmala-gpg'
[sachin.chemmala-gpg 276b8f2] Uploading Public GPG Key: sachin.chemmala.asc
 1 file changed, 64 insertions(+)
 create mode 100644 provisioning/keys/sachin.chemmala.asc
To github.com:blinkhealth/eng-onboarding.git
 ! [rejected]        sachin.chemmala-gpg -> sachin.chemmala-gpg (non-fast-forward)
error: failed to push some refs to 'github.com:blinkhealth/eng-onboarding.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   188  100    90  100    98    206    224 --:--:-- --:--:-- --:--:--   436
Pull request created successfully!
```

2023-09-14 10:22 UTC, sachinchemmala requested changes

2023-09-14 10:22 UTC, sachinchemmala commented on provisioning/onboard/public_key_upload.sh
> +rm -rf "$TEMP_DIR"
As I mentioned in the previous review can you please add a message like `cleanup is success/failure`

2023-09-14 10:22 UTC, sachinchemmala commented on provisioning/onboard/public_key_upload.sh
> +        mkdir -p "$TEMP_DIR/provisioning/keys"
This folder should exists already right, why are we running it again ?

2023-09-14 13:31 UTC, sachinchemmala commented
still failing. I tied with wrong token and below is the output

```
─$ bash ~/test/pr.sh
Enter your GitHub personal access token:
Cloning into '/var/folders/65/g18dz1q121q1_9r94m7ntzh40000gp/T/eng-onboarding.UU8jsMPO'...
remote: Enumerating objects: 140, done.
remote: Counting objects: 100% (70/70), done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 140 (delta 43), reused 50 (delta 28), pack-reused 70
Receiving objects: 100% (140/140), 43.59 KiB | 65.00 KiB/s, done.
Resolving deltas: 100% (62/62), done.
jq: error (at <stdin>:4): Cannot index object with number
Switched to a new branch 'sachin.chemmala-gpg'
[sachin.chemmala-gpg 6952348] Uploading Public GPG Key: sachin.chemmala.asc
 1 file changed, 64 insertions(+)
 create mode 100644 provisioning/keys/sachin.chemmala.asc
To github.com:blinkhealth/eng-onboarding.git
 ! [rejected]        sachin.chemmala-gpg -> sachin.chemmala-gpg (non-fast-forward)
error: failed to push some refs to 'github.com:blinkhealth/eng-onboarding.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Pull request created successfully!
Cleanup successful. Temporary directory deleted.
```

2023-09-20 09:10 UTC, sachinchemmala commented on provisioning/onboard/public_key_upload.sh
> +        gh pr create --base "$BASE_BRANCH" --head "$REPO_OWNER:$BRANCH_NAME" -R "$REPO_OWNER/$REPO_NAME" --title "Request to add GPG key: $MACHINE_USERNAME.asc" --body "This PR adds the GPG key of $M
you might need to validate if `gh` is installed or not. or you will get error like `command not found: gh`

2023-09-20 09:11 UTC, vishnureddy-blink commented on provisioning/onboard/public_key_upload.sh
> +        gh pr create --base "$BASE_BRANCH" --head "$REPO_OWNER:$BRANCH_NAME" -R "$REPO_OWNER/$REPO_NAME" --title "Request to add GPG key: $MACHINE_USERNAME.asc" --body "This PR adds the GPG key of $M
I will install gh while installing dependencies here: https://github.com/blinkhealth/eng-onboarding/blob/main/provisioning/onboard/depdendency.sh

2023-09-20 09:11 UTC, sachinchemmala commented on provisioning/onboard/public_key_upload.sh
> +    PR_STATUS=$(curl -s -H "Authorization: token YOUR_GITHUB_TOKEN" \
we are not using token right ?

2023-09-20 09:15 UTC, sachinchemmala commented on provisioning/onboard/public_key_upload.sh
> +    echo "Cleanup successful. Temporary directory deleted."
nit: change to `Temp dir $TEMP_DIR cleaned up successfully`

2023-09-20 09:15 UTC, sachinchemmala commented on provisioning/onboard/public_key_upload.sh
> +    echo "Cleanup failed. Please manually delete the temporary directory: $TEMP_DIR"
nit: change to - ` Clean up of temp dir $TEMP_DIR failed`

2023-09-20 14:48 UTC, satyen-blink requested changes

2023-09-20 14:48 UTC, satyen-blink commented on provisioning/onboard/public_key_upload.sh
> +if [ -f "$TEMP_DIR/provisioning/keys/$MACHINE_USERNAME.asc" ]; then
will this location ever change?

2023-09-20 14:48 UTC, satyen-blink commented on provisioning/onboard/public_key_upload.sh
> +        exit 1
exit 1 - is an error state.. is this an error state or a successful error?  If it's OK to be in this state - use `exit 0`

Also I think the `-n` is incorrect and it should be `-z`, since you want check for `null` or `empty` string.  I prefer `-z` because if there is no status . .then you have an error state and exit with 1

2023-09-20 14:48 UTC, satyen-blink commented on provisioning/onboard/public_key_upload.sh
> +        cp "$LOCAL_FILE" "$TEMP_DIR/provisioning/keys/$MACHINE_USERNAME.asc"
make this variable so that you're not repeating it.. and use the variable like `$LOCAL_FILE`

2023-09-20 14:48 UTC, satyen-blink commented on provisioning/onboard/public_key_upload.sh
> +        git --git-dir="$TEMP_DIR/.git" --work-tree="$TEMP_DIR" add "provisioning/keys/$MACHINE_USERNAME.asc"
same here for `provisioning/keys/...`

2023-09-20 14:48 UTC, satyen-blink commented on provisioning/onboard/public_key_upload.sh
> +#!/bin/bash
below here.. _please_ add doc strings  here and for all other scripts to be written. ... to explain the goal if this script.. and link to any other external wiki's.

When the Human reads the doc strings.. it will easy for them to get the context.

example. 
```
# The script does X because it's required by Y, A, B , C and is part of Z.  Upon failure the Human should do P and or follow the wiki <here>
# Example of how to run this script
# git clone <blah>
# public_key_upload.sh -help
# public_key_upload.sh < any other flag_option1> < flag_option2> etc... 
```

2023-09-22 00:08 UTC, satyen-blink requested changes
thanks for the changes.. let's sync up on the doc strings offline.

2023-09-22 00:08 UTC, satyen-blink commented on provisioning/onboard/public_key_upload.sh
> +KEY_DIRECTORY="$TEMP_DIR/provisioning/keys"
This is fine the way it is - no need to change it...  but be careful when you do `$TEMP_DIR/a/b/c` vs `${TEMP_DIR}/a/b/c`. The interpolation varies.

2023-09-22 00:08 UTC, satyen-blink commented on provisioning/onboard/public_key_upload.sh
> +KEY_FILENAME="$MACHINE_USERNAME.asc"
use `${MACHINE_USERNAME}` here as a good practice.

2023-09-25 13:05 UTC, vishnureddy-blink commented on provisioning/onboard/public_key_upload.sh
> +KEY_DIRECTORY="$TEMP_DIR/provisioning/keys"
I will write trouble shoot wiki in confluence

2023-09-25 13:07 UTC, vishnureddy-blink commented on provisioning/onboard/public_key_upload.sh
> +if [ -f "$TEMP_DIR/provisioning/keys/$MACHINE_USERNAME.asc" ]; then
No

2023-09-25 13:08 UTC, vishnureddy-blink commented on provisioning/onboard/public_key_upload.sh
> +        exit 1
changed

2023-09-29 15:44 UTC, satyen-blink requested changes

2023-09-29 15:44 UTC, satyen-blink commented on provisioning/onboard/public_key_upload.sh
> +# Define the destination directory path for the key
i think i made a comment to remove these comments.. for every line of code you have.. please do it .

2023-09-29 15:44 UTC, satyen-blink commented on provisioning/onboard/public_key_upload.sh
> +# Clone the Repository using SSH into the Temporary Directory
like this one.. one don't need the comment.

2023-09-29 15:44 UTC, satyen-blink commented on provisioning/onboard/public_key_upload.sh
> +        # Commit the Changes
and here

2023-09-29 15:44 UTC, satyen-blink commented on provisioning/onboard/public_key_upload.sh
> +        # Add the Specific File to the Staging
and here

2023-09-29 15:44 UTC, satyen-blink commented on provisioning/onboard/public_key_upload.sh
> +        # Copy the Public Key to the Keys Directory and Rename it
here.. etc..

2023-09-29 16:03 UTC, merged