removing user from mysql DB
blinkhealth/eng-onboarding pull request #7
Opened 2023-07-17 13:12 UTC by vishnureddy-blink

https://blinkhealth.atlassian.net/browse/INFRAENG-3481

2023-07-17 16:59 UTC, satyen-blink requested changes

2023-07-17 16:59 UTC, satyen-blink commented on provisioning/offboard/database.sh
> +read -p "Enter the exact user you want to delete: " user_to_delete
After thought.. if you want to search for users.. put it behind a flag so default is to delete.
and flag is there just to do the search.
It removes a lot of human input prompts that don't need to be there.

Less prompts the better.

2023-07-17 16:59 UTC, satyen-blink commented on provisioning/offboard/database.sh
> +#!/bin/bash
Please do not call the script `database.sh` re-name it to something more informative. and DO add lots of doc strings to explain what this thing does.

2023-07-17 17:21 UTC, satyen-blink requested changes
Makes the changes that you see fit - after offline discussion.

At least add doc strings for the next person.

2023-07-18 17:56 UTC, satyen-blink commented on provisioning/offboard/mysql-user-remove.sh
> +# This script is to remove user from Dev & Prod e-commerce backenend DB
excellent

2023-07-18 17:56 UTC, satyen-blink commented on provisioning/offboard/mysql-user-remove.sh
> +echo "$matching_users"
echo "Found: $matching_users" 

just be careful as to what the user sees, are there new lines in the output?

2023-07-18 17:59 UTC, vishnureddy-blink commented on provisioning/offboard/mysql-user-remove.sh
> +echo "$matching_users"
No Satyen, just minimised the code as much as possible and added doc strings as per your suggestion . I will write Runbook user deletion in detail .

2023-07-19 03:17 UTC, merged